<h1>ADD</h1>
<?php

$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';
foreach ($this->form1 as $element) {
    if (!$element instanceof Zend\Form\Element\Submit) {
        ?>
        <div class="control-group">
            <label class="control-label" for="<?php echo $element->getName();?>">
                <?php echo $this->translate($element->getLabel());?>
            </label>
            <div class="controls">
                <?php echo $this->formElement($element) ?>
                <?php echo $this->formElementErrors($element);?>
            </div>
        </div>
        <?php
    } else {
        $element->setAttribute('class', 'btn btn-primary');
        ?>
        <div class="form-actions">
            <?php echo $this->formElement($element);?>
        </div>
        <?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag();